spring:
  kafka:
    bootstrap-servers:
      -
  rabbitmq:
    template:
      exchange:
      routing-key:
      receive-timeout:
    host: localhost
    port: 5672
    username:
    password:
  datasource:
    username: sa
    password: password
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    init : true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  data:
    rest:
      base-path: /api

